//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaQueueTareas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int id { get; set; }
        public string id_user { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int id_priority { get; set; }
        public int id_state { get; set; }
        public string log { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_ejecucion { get; set; }
        public Nullable<System.DateTime> fecha_finalizacion { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual State State { get; set; }
    }
}
